trigger:
  branches:
    include:
      - master
      - refs/tags/*
stages:
  - stage: Build
    jobs:
    - job: BuildSwiftUIGlueAndNuGets
      displayName: 'Building Swift UI'
      pool:
        vmImage: macOS-latest
      steps:
      - task: NuGetToolInstaller@1
      - task: MSBuild@1
        displayName: 'Building Swift UI Glue and NuGets via build.proj'
        inputs:
          solution: build.proj
          configuration: Release
          msbuildArguments: /restore /v:diag
    - job: BuildTestProjects
      displayName: Building Test Projects
      dependsOn: BuildSwiftUIGlueAndNuGets
      pool:
        vmImage: macOS-latest
      steps:
      - task: NuGetToolInstaller@1
      - task: MSBuild@1
        displayName: 'Build MacOS C# project XamMacSwiftUITest/XamMacSwiftUITest.csproj'
        inputs:
          solution: XamMacSwiftUITest/XamMacSwiftUITest.csproj
          configuration: Release
          msbuildArguments: /restore /v:diag
      - task: MSBuild@1
        displayName: 'Build MacOS F# project XamMacSwiftUITest.FSharp/XamMacSwiftUITest.FSharp.csproj'
        inputs:
          solution: XamMacSwiftUITest.FSharp/XamMacSwiftUITest.FSharp.csproj
          configuration: Release
          msbuildArguments: /restore /v:diag
      - task: MSBuild@1
        displayName: 'Build iOS C# project XamiOSSwiftUITest/XamiOSSwiftUITest.csproj'
        inputs:
          solution: XamiOSSwiftUITest/XamiOSSwiftUITest.csproj
          configuration: Release
          msbuildArguments: /restore /v:diag